### ISSUE TITLE
[BUG] Can't apply a resource if it's too big

### ISSUE THREAD

**Issue by ryanzhang-oss** [Azure/fleet#295]
### **Describe the bug**
The three way merge annotation hits the annotation length limit

```
'Failed to apply manifest: Secret "sh.helm.release.v1.ryan-redis.v1"
          is invalid: metadata.annotations: Too long: must have at most 262144 bytes'
```

### **Environment**
Please provide the following: 
- Hub cluster details
- Member cluster details

### **To Reproduce**
[Follow the steps of the redis install guide](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/run-scalable-and-resilient-redis-with-kubernetes-and-azure/ba-p/3247956)

### **Expected behavior**
The secret should be omitted as it's created by the helm. This bug actually makes it work.

### **Screenshots**
```shell
 status:
    conditions:
    - lastTransitionTime: "2022-09-16T18:57:06Z"
      message: Successfully scheduled resources for placement
      observedGeneration: 1
      reason: ScheduleSucceeded
      status: "True"
      type: Scheduled
    - lastTransitionTime: "2022-09-16T21:14:48Z"
      message: there are failed to apply manifests, please check the `failedResourcePlacements`
        status
      observedGeneration: 1
      reason: ApplyFailed
      status: "False"
      type: Applied
    failedPlacements:
    - clusterName: member1
      condition:
        lastTransitionTime: "2022-09-16T21:14:47Z"
        message: 'Failed to apply manifest: Secret "sh.helm.release.v1.ryan-redis.v1"
          is invalid: metadata.annotations: Too long: must have at most 262144 bytes'
        reason: appliedManifestFailed
        status: "False"
        type: Applied
      kind: Secret
      name: sh.helm.release.v1.ryan-redis.v1
      namespace: redis-test
      version: v1
    - clusterName: member2
      condition:
        lastTransitionTime: "2022-09-16T21:14:46Z"
        message: 'Failed to apply manifest: Secret "sh.helm.release.v1.ryan-redis.v1"
          is invalid: metadata.annotations: Too long: must have at most 262144 bytes'
        reason: appliedManifestFailed
        status: "False"
        type: Applied
      kind: Secret
      name: sh.helm.release.v1.ryan-redis.v1
      namespace: redis-test
      version: v1

```

**Comment by Arvindthiru** [comment]
https://msazure.visualstudio.com/CloudNativeCompute/_wiki/wikis/CloudNativeCompute.wiki/392496/Annotation-Limit

**Comment by Arvindthiru** [comment]
The config map approach seems to be the best bet as it provide a k8s native approach to store large values which could not be stored as an annotation. But a key thing to keep in mind is that the config map has a max limit of 1MB if the manifest size somehow so large that it exceeds this limit we may run into a similar error.

If we consistently run into this the 1MB limit issue for the config map after we make the proposed change in the future we may have to look into using a third party storage solution running as a pod on the hub cluster, but doing this introduces an extra dependency for us to manage
