### ISSUE TITLE
Allow three-way merge when last applied configuration is missing

### ISSUE THREAD

**Issue by michaelawyu** [Azure/fleet#349]
At this moment, work controller will refuse to process objects if no last applied configuration is present ([code](https://github.com/Azure/fleet/blob/738a350e324c5bcd47b36358982aafc38934bc9e/pkg/controllers/work/patch_util.go#L114)). If the last applied configuration annotation is missing from objects for any reason (e.g. user tampering), the system will be trapped in an error loop.

During on-duty session, we have identified two clusters so far which are suffering from this pattern; since Kubernetes three-way merge algorithm itself does accept objects w/o last applied configuration ([code](https://github.com/kubernetes/apimachinery/blob/5d4cdd22b0f7c364f4113b8bb2086763cf2a131c/pkg/util/strategicpatch/patch.go#L2048)), we could solve this pattern by dropping the requirement from our end as well.

See the discussion in on-duty channel for impact clusters.

**Comment by Arvindthiru** [comment]
https://github.com/Azure/fleet/pull/353
