### ISSUE TITLE
[feature] Add AllowedAPIs option for the resources propagated from the namespace

### ISSUE THREAD

**Issue by vasudev-bongale** [Azure/fleet#633]
```
// SkippedPropagatingAPIs indicates comma separated resources that should be skipped for propagating.
SkippedPropagatingAPIs string
```
All resources in the namespace configured with CRP are propagated to the member clusters by default. The hub agent option [`SkippedPropagatingAPIs`](https://github.com/Azure/fleet/blob/6fd37978c0f695b702a069ca6cf9e96c0d2585dc/cmd/hubagent/options/options.go#L52C1-L52C1) can be used to exclude propagating certain APIs from the namespace. The list of skipped APIs can get long to specify all resources and it needs to be updated when the new use cases come up. Alternatively an `AllowedAPIs` option can allow us to be selective while propagating resources. Having a limited set of allowed resources should also reduce reconciliations on the CRPs as it might not trigger on any change in the namespace.

**Comment by zhiying-lin** [comment]
It looks good to me. [SkippedPropagatingAPIs](https://github.com/Azure/fleet/blob/6fd37978c0f695b702a069ca6cf9e96c0d2585dc/cmd/hubagent/options/options.go#L52C1-L52C1) and `AllowedAPIs` should be exclusive.
