### ISSUE TITLE
[Improvement] Provide better output on "kubectl get" and "kubectl get -o wide"

### ISSUE THREAD

**Issue by serbrech** [Azure/fleet#793]
Wide output is the same as normal output

kubectl get crp/place-ns
NAME       GEN   SCHEDULED   SCHEDULEDGEN   APPLIED   APPLIEDGEN   AGE
place-ns   2     True        2              True      2            47s

kubectl get crp/place-ns -o wide
NAME       GEN   SCHEDULED   SCHEDULEDGEN   APPLIED   APPLIEDGEN   AGE
place-ns   2     True        2              True      2            50s

**Comment by zhiying-lin** [comment]
Thank you for catching this. The fix has been merged.
