### ISSUE TITLE
[BUG] don't log "Ignoring update events that are irrelevant to the scheduler"

### ISSUE THREAD

**Issue by serbrech** [Azure/fleet#794]
### **Describe the bug**

[Ignoring update Info log](https://github.com/Azure/fleet/blob/17a0f92fafb46db72c87ee0a50075652342a3dd8/pkg/scheduler/watchers/membercluster/watcher.go#L266C4-L266C112)

This is very verbose and drowns all other logs.
it shouldn't be Info level.

**Comment by Arvindthiru** [comment]
Was handled as part of this PR https://github.com/Azure/fleet/pull/795
